server:
  port: 0
#server:
#  port: 9140
spring:
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: ${zipkin.url:http://192.168.99.100:9411/}
  mvc:
    view:
      suffix: .html
      prefix: /
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: ${orderms.datasource.url:jdbc:h2:mem:currencyfactormsDb;DB_CLOSE_DELAY=-1}
    username: ${orderms.datasource.username:sa}
    password: ${orderms.datasource.password:}
    driver-class-name: ${orderms.datasource.driver:org.h2.Driver}
  jpa:
    show-sql: true
  cloud:
    bus:
      destination: configXchange
    stream:
     #rabbit:
      bindings:
        webaudit-out: 
         destination: ex.webaudit
         group: q.audit
         producer:
          bindQueue: false
          routing-key-expression: '"rk.webaudit.shim.him"'
          routing-key: '"rk.webaudit.shim.him"'
          routingKeyExpression: '''rk.webaudit.shim.him''' 
          
  rabbitmq:
    host: ${rabbitmq.host:rabbitmqmaster}
    port: ${rabbitmq.port:5672}
    
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: ${accountloginms.eureka.url:http://192.168.99.1:8761/eureka}
management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
        loggerLevel: basic 
         


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
        timeout:
          enabled: false          


jwtSecret: mySecretKey
jwtExpirationMs: 86400000
    

